// Saifu Web's service worker (T-030-19; features/030-saifu/plan.md §5.1a;
// NFR-3, REQ-AP-5): generated into the web export, so that after one visit the
// app opens with no network and produces access passes on the device.
//
// - Every file of the export is cached when the worker installs, under a cache
//   named for the export's contents, so a new build replaces the old cache.
// - A page load asks the network first and falls back to the cached app, so an
//   online holder always gets the current build, and every path — `/checkout`
//   and `/invitations` included — opens offline.
// - The export's files are served from the cache. Nothing else is cached: calls
//   to the ledger, the sponsor relay and Kippu go to other origins, untouched.
//   The holder's tickets are kept by the app's own device cache, as natively,
//   and the holder record in IndexedDB.

import { createHash } from "node:crypto";

/** The service worker's own path; never cached by the worker. */
export const SERVICE_WORKER_PATH = "/sw.js";

/** The URL paths the worker caches, from the export's files (paths relative to its root). */
export function precachePaths(files: readonly string[]): string[] {
  return files
    .map((file) => `/${file.split("\\").join("/").replace(/^\/+/, "")}`)
    .filter((path) => path !== SERVICE_WORKER_PATH && !path.endsWith(".map"))
    .sort();
}

/** The cache name: the export's paths and contents, hashed. */
export function cacheName(contents: ReadonlyMap<string, Uint8Array>): string {
  const hash = createHash("sha256");
  for (const path of [...contents.keys()].sort()) {
    hash
      .update(path)
      .update("\0")
      .update(contents.get(path) ?? new Uint8Array())
      .update("\0");
  }
  return `saifu-${hash.digest("hex").slice(0, 16)}`;
}

/** The worker's source. */
export function serviceWorkerSource(cache: string, paths: readonly string[]): string {
  return `// Generated by tools/web/service-worker.ts for this build. Do not edit.
const CACHE = ${JSON.stringify(cache)};
const PRECACHE = ${JSON.stringify(paths)};
const APP = "/index.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((path) => new Request(path, { cache: "reload" }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((key) => key.startsWith("saifu-") && key !== CACHE).map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches.open(CACHE).then((cache) => cache.match(APP)).then((app) => app ?? Response.error()),
      ),
    );
    return;
  }
  if (!PRECACHE.includes(url.pathname)) return;
  event.respondWith(
    caches.open(CACHE).then((cache) => cache.match(url.pathname)).then((hit) => hit ?? fetch(request)),
  );
});
`;
}
